spring:
  profiles:
    active: dev

  # Email configuration
  mail:
    host: smtp.strato.de
    port: 465
    username: mail@team-solutions.net
    password:
    properties.mail:
      transport-protocol: smtp
      smtp:
        ssl.trust: smtp.strato.de
        auth: true
        starttls.enable: true

